APP          = APP_NAME

# Leave this blank while building project
WORKSPACE    = WORKSPACE_NAME

# Specify project name if there's no WORKSPACE
PROJECT      = PROJECT_NAME

CONFIG       = InHouse
SCHEME       = APP_INHOUSE
ICON_NAME    = AppIcon60x60@2x.png

# iMessage addresses list seperated with white space
IMSG_LIST    = a_imessage_email@mac.com +86.18621800000 another_email@me.com

# Comment the following line if you prefer Bonjour Network
# BASE_URL     = http://ota.nsnotfound.com

# Your Mailgun mail list
EMAIL_LIST   = newproject@lexrus.mailgun.org
EMAIL_DOMAIN = lexrus.mailgun.org

# Get API key from Keychain by item name "mailgun api key"
MAILGUN_API_KEY = $(shell security find-generic-password -l "mailgun api key" -gw)

# Your server with SSH access
SFTP_SERVER  = lexrus@nsnotfound.com
SFTP_PATH    = /var/www/ota
SFTP_PORT    = 22

# Share via Apple Bonjour Network
BASE_PORT    = 9966
BASE_URL    ?= http://$(shell scutil --get ComputerName).local:$(BASE_PORT)

# Shorten URL by lexr.us
# Change or comment this line if you prefer goo.gl
LEXR_US      = YES

# TestFlight Tokens
TESTFLIGHT_API_TOKEN  = __GET_IT_FROM__https://testflightapp.com/account/#api
TESTFLIGHT_TEAM_TOKEN = __GET_IT_FROM__https://testflightapp.com/dashboard/team/edit/

# HockeyApp Token
HOCKEY_APP_API_TOKEN  = __GET_IT_FROM__https://rink.hockeyapp.net/manage/auth_tokens